//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 08:43:43 PM GMT 
//


package ie.gmit.sw.ds.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vehiclePlate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="availableIndicator" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vehicle_SID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", namespace = "http://sw.gmit.ie/ds/model", propOrder = {
    "vehiclePlate",
    "availableIndicator",
    "model"
})
public class Vehicle implements Serializable {

    @XmlElement(namespace = "http://sw.gmit.ie/ds/model", required = true)
    protected String vehiclePlate;
    @XmlElement(namespace = "http://sw.gmit.ie/ds/model")
    protected int availableIndicator;
    @XmlElement(namespace = "http://sw.gmit.ie/ds/model", required = true)
    protected String model;
    @XmlAttribute(name = "vehicle_SID")
    protected String vehicleSID;

    /**
     * Gets the value of the vehiclePlate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    
    public String getVehiclePlate() {
        return vehiclePlate;
    }
public Vehicle() {}
    public Vehicle(String vehiclePlate, int availableIndicator, String model, String vehicleSID) {
		super();
		this.vehiclePlate = vehiclePlate;
		this.availableIndicator = availableIndicator;
		this.model = model;
		this.vehicleSID = vehicleSID;
	}

	/**
     * Sets the value of the vehiclePlate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiclePlate(String value) {
        this.vehiclePlate = value;
    }

    /**
     * Gets the value of the availableIndicator property.
     * 
     */
    public int getAvailableIndicator() {
        return availableIndicator;
    }

    /**
     * Sets the value of the availableIndicator property.
     * 
     */
    public void setAvailableIndicator(int value) {
        this.availableIndicator = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the vehicleSID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleSID() {
        return vehicleSID;
    }

    /**
     * Sets the value of the vehicleSID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleSID(String value) {
        this.vehicleSID = value;
    }

}
